CREATE TABLE fancyplants_plants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trefle_id INTEGER UNIQUE NOT NULL,
    scientific_name TEXT NOT NULL,
    common_name TEXT,
    image TEXT
);