CREATE TABLE fancyplants_plant_instances (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES fancyplants_users(id) ON DELETE CASCADE NOT NULL,
    trefle_id INTEGER
        REFERENCES fancyplants_plants(trefle_id) ON DELETE CASCADE NOT NULL,
    note TEXT,
    watered_date TEXT
);